import Head from 'next/head'
import styles from '../../styles/Home.module.css'
import Link from 'next/link'
import { getScore } from "../../lib/cms_if"

export async function getServerSideProps ( { params } ) {
  let scores = await getScore(params.gameid);

  return {
    props: {
      scores: scores
    }
  }
}

function ScoreData ( {scoreinfo} ) {
  console.log(scoreinfo)

  return <dl>
    <dt>Player Initials:</dt>
    <dd>{scoreinfo.player_handle}</dd>


    <dt>Points Scored:</dt>
    <dd>{scoreinfo.points_scored}</dd>

    <dt>Ship Used:</dt>
    <dd>{scoreinfo.ship_used}</dd>

    <dt>Targets Destroyed:</dt>
    <dd>{scoreinfo.targets_destroyed}</dd>

    <dt>Gametime (sec):</dt>
    <dd>{scoreinfo.time_played}</dd>
  </dl>
}

export default function Score(props) {
  let scores = props.scores;

  return (
    <div className={styles.container}>
      <Head>
        <title>Space Invaders - {scores[0].player_handle}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Space Invaders, {scores[0].player_handle}
        </h1>

        <div>
          {scores && 
            scores.map( (score, idx) => <>
              <ScoreData scoreinfo={score} />
            </>)
          }
        </div>

        <div><Link href="/">Return Home</Link></div>
      </main>

      <footer className={styles.footer}>
        <div>
          CS55.13 Final Project
        </div>
      </footer>
    </div>
  )
}
