import Head from 'next/head'
import styles from '../../styles/Home.module.css'
import Link from 'next/link'
import { useRouter } from 'next/router'
import { getScores } from "../../lib/cms_if"

export async function getServerSideProps () {
  return {
    props: {
    }
  }
}

export default function Scores(props) {
  const scores = getScores();
  const router = useRouter();
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Space Invaders - High Scores</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Space Invaders, High Scores
        </h1>

        <ul>
          {scores && 
            scores.map( (score, idx) => {
              return <li key={"gameid_"+idx}>
                <Link href={`${router.asPath}/${score.id}`}>
                  {score.player_handle} - {score.points_scored}
                </Link>
              </li>
            })
          }
        </ul>

        <div><Link href="/">Return Home</Link></div>
      </main>

      <footer className={styles.footer}>
        <div>
          CS55.13 Final Project
        </div>
      </footer>
    </div>
  )
}
