import Head from 'next/head'
import styles from '../../styles/Home.module.css'
import Link from 'next/link'
import { getLevel } from "../../lib/cms_if"

export async function getServerSideProps ( { params } ) {
  let levels = await getLevel(params.level);

  return {
    props: {
      levels: levels
    }
  }
}

function LevelInfo ( {levelinfo} ) {
  console.log(levelinfo)

  return <dl>
    <dt>Level Name:</dt>
    <dd>{levelinfo.level_name}</dd>

    <dt>Background Color:</dt>
    <dd>{levelinfo.background_color}</dd>

    <dt>Description:</dt>
    <dd>{levelinfo.post_content}</dd>
  </dl>
}

export default function Level(props) {
  let levels = props.levels;

  return (
    <div className={styles.container}>
      <Head>
        <title>Space Invaders - {levels[0].level_name}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Space Invaders, {levels[0].level_name}
        </h1>

        <div>
          {levels && 
            levels.map( (level, idx) => <>
              <LevelInfo levelinfo={level} />
            </>)
          }
        </div>

        <div><Link href="/">Return Home</Link></div>
      </main>

      <footer className={styles.footer}>
        <div>
          CS55.13 Final Project
        </div>
      </footer>
    </div>
  )
}
