import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Space Invaders, CMS Powered
        </h1>

        <ul>
          <li><Link href="/ships">Spaceships</Link></li>
          <li><Link href="/scores">High Scores</Link></li>
          <li><Link href="/levels">Levels</Link></li>
        </ul>
      </main>

      <footer className={styles.footer}>
        <div>
          CS55.13 Final Project
        </div>
      </footer>
    </div>
  )
}
