import Head from 'next/head'
import styles from '../../styles/Home.module.css'
import Link from 'next/link'
import { getShip } from "../../lib/cms_if"

export async function getServerSideProps ( { params } ) {
  let ships = await getShip(params.ship);

  return {
    props: {
      ships: ships
    }
  }
}

function ShipData ( {shipinfo} ) {
  console.log(shipinfo)

  return <dl>
    <dt>Ship Type:</dt>
    <dd>{shipinfo.shiptype}</dd>

    <dt>Ammo:</dt>
    <dd>{shipinfo.ammo}</dd>

    <dt>Firepower:</dt>
    <dd>{shipinfo.firepower}</dd>

    <dt>Armor:</dt>
    <dd>{shipinfo.armor}</dd>

    <dt>Speed:</dt>
    <dd>{shipinfo.speed}</dd>
  </dl>
}

export default function Ship(props) {
  let ships = props.ships;

  return (
    <div className={styles.container}>
      <Head>
        <title>Space Invaders - {ships[0].shiptype}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Space Invaders, {ships[0].shiptype}
        </h1>

        <div>
          {ships && 
            ships.map( (ship, idx) => <>
              <ShipData shipinfo={ship} />
            </>)
          }
        </div>

        <div><Link href="/">Return Home</Link></div>
      </main>

      <footer className={styles.footer}>
        <div>
          CS55.13 Final Project
        </div>
      </footer>
    </div>
  )
}
